# Loading prepared data (train and test)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
X_train = pd.read_csv('/content/drive/My Drive/titanic/train_dataset.csv')
X_test = pd.read_csv('/content/drive/My Drive/titanic/test_dataset.csv')

In [ ]:
print(X_train.shape)
print(X_test.shape)

(891, 12)
(418, 12)


In [ ]:
train= pd.read_csv('/content/drive/My Drive/titanic/train.csv')
y_train= train['Survived']

In [ ]:
y_train.shape

(891,)

# Trying out different models

In [ ]:
## Method for parameter tuning

In [ ]:
# break train dataset using train test split to train and cv
# based on 1 parameter train and find cv accuracy
# do this for all parameters
# plot graph

In [ ]:
# def find_parameters(estimator, list):

**Decision Tree**

In [ ]:
>>> from sklearn.model_selection import cross_val_score
>>> from sklearn.tree import DecisionTreeClassifier

max_depth= [5, 10, 15, 50, None]
min_samples_split=[2, 5]
for d in max_depth:
  for s in min_samples_split:
    clf = DecisionTreeClassifier(max_depth=d, min_samples_split=s)
    cv_scores= cross_val_score(clf, X_train, y_train, cv=5, 
                  scoring='accuracy')
    print(cv_scores, cv_scores.mean(), d, s)

[0.75418994 0.80898876 0.82022472 0.78089888 0.80898876] 0.7946582135459168 5 2
[0.75418994 0.80898876 0.82022472 0.78089888 0.80898876] 0.7946582135459168 5 5
[0.70949721 0.81460674 0.85955056 0.79775281 0.82022472] 0.8003264076329171 10 2
[0.72067039 0.81460674 0.86516854 0.79775281 0.8258427 ] 0.8048082355156613 10 5
[0.72625698 0.79775281 0.83146067 0.79775281 0.81460674] 0.7935660033896177 15 2
[0.73743017 0.80337079 0.84269663 0.79213483 0.82022472] 0.7991714267779801 15 5
[0.73184358 0.80337079 0.8258427  0.79775281 0.79775281] 0.791312535308518 50 2
[0.74301676 0.80337079 0.83707865 0.79775281 0.83146067] 0.8025359362249702 50 5
[0.73184358 0.80337079 0.8258427  0.78089888 0.83707865] 0.7958069173309898 None 2
[0.74301676 0.79775281 0.83707865 0.79213483 0.81460674] 0.7969179586968803 None 5


In [ ]:
# Decision Tree
# Decision Forrest
# GBDT
# Naive Bayes
# SVM
# KNN
# Logistoc Regression

**SVM**

In [ ]:
from sklearn.svm import SVC

C=[10**-2 , 10**-1 ,10**0 ,10**1 ,10**2 ]
for c in C:
  clf = SVC(C=c)
  cv_scores= cross_val_score(clf, X_train, y_train, cv=5, 
                  scoring='accuracy')
  print(cv_scores, cv_scores.mean())

# Best C=10

[0.61452514 0.61797753 0.61797753 0.61797753 0.61235955] 0.6161634548992531
[0.79329609 0.79213483 0.79213483 0.7752809  0.81460674] 0.7934906785512523
[0.77094972 0.79775281 0.80898876 0.78089888 0.82022472] 0.7957629778419434
[0.78212291 0.78651685 0.81460674 0.79775281 0.82022472] 0.8002448057246877
[0.7877095  0.7752809  0.81460674 0.81460674 0.83146067] 0.8047329106772958


**GBDT**

In [ ]:
>>> from sklearn.ensemble import GradientBoostingClassifier

learning_rate= [0.1, 0.05]
n_estimators= [100, 200, 400, 500]

for l in learning_rate:
  for e in n_estimators:
    clf=GradientBoostingClassifier(learning_rate=l, n_estimators=e)
    cv_scores= cross_val_score(clf, X_train, y_train, cv=5, 
                      scoring='accuracy')
    print(cv_scores, cv_scores.mean(),l,e)

# learning_rate=.05
# n_estimators=200

[0.7877095  0.78651685 0.87078652 0.79213483 0.80898876] 0.8092272926997678 0.1 100
[0.77094972 0.79775281 0.85393258 0.79213483 0.8258427 ] 0.8081225284037412 0.1 200
[0.75418994 0.76966292 0.85955056 0.82022472 0.83707865] 0.8081413596133326 0.1 400
[0.75418994 0.76404494 0.85393258 0.83146067 0.83146067] 0.8070177641077144 0.1 500
[0.77653631 0.80337079 0.84269663 0.78089888 0.80337079] 0.8013746783001695 0.05 100
[0.7877095  0.78651685 0.85955056 0.79775281 0.82022472] 0.8103508882053857 0.05 200
[0.77094972 0.79775281 0.85955056 0.80337079 0.8258427 ] 0.811493314920595 0.05 400
[0.75977654 0.79213483 0.86516854 0.8258427  0.83146067] 0.8148766555771767 0.05 500


**Naive Bayes**

In [ ]:
>>> from sklearn.naive_bayes import GaussianNB
>>> clf = GaussianNB()
cv_scores= cross_val_score(clf, X_train, y_train, cv=5, 
                  scoring='accuracy')
print(cv_scores, cv_scores.mean())


[0.65363128 0.74157303 0.78651685 0.78651685 0.80337079] 0.7543217626012179


**Logistic Regression**

In [ ]:
>>> from sklearn.linear_model import LogisticRegression
C=[10**-2 , 10**-1 ,10**0 ,10**1 ,10**2 ]
for c in C:
  clf = LogisticRegression(C=c)
  cv_scores= cross_val_score(clf, X_train, y_train, cv=5, 
                  scoring='accuracy')
  print(cv_scores, cv_scores.mean())

# Best C=1

[0.68715084 0.78089888 0.75280899 0.76404494 0.78651685] 0.7542841001820351
[0.7150838  0.81460674 0.81460674 0.76404494 0.80898876] 0.7834661979787836
[0.7877095  0.79775281 0.78651685 0.78089888 0.80898876] 0.7923733601154981
[0.7877095  0.79775281 0.79213483 0.78089888 0.80337079] 0.7923733601154981
[0.7877095  0.79775281 0.79213483 0.78089888 0.80337079] 0.7923733601154981


**KNN**

In [ ]:
>>> from sklearn.neighbors import KNeighborsClassifier
K=[1,3,5,15,20,25,50]
for k in K:
  clf = KNeighborsClassifier(n_neighbors=k)
  cv_scores= cross_val_score(clf, X_train, y_train, cv=5, 
                  scoring='accuracy')
  print(cv_scores, cv_scores.mean())

  # Best k=15 

[0.70391061 0.74157303 0.75280899 0.78089888 0.76404494] 0.7486472914443538
[0.74301676 0.7247191  0.78651685 0.79213483 0.78089888] 0.765457284539577
[0.72625698 0.74157303 0.81460674 0.79213483 0.79775281] 0.774464879794112
[0.74860335 0.76404494 0.80337079 0.76966292 0.8258427 ] 0.7823049400539828
[0.74301676 0.76404494 0.80898876 0.76966292 0.80337079] 0.7778168351013746
[0.68715084 0.74157303 0.80898876 0.78651685 0.80337079] 0.7655200552382148
[0.6424581  0.75280899 0.76404494 0.78089888 0.76966292] 0.7419747661791476


**Ensambling : DT,SVM,GBDT,LR,KN**

In [ ]:
>>> from sklearn.ensemble import StackingClassifier

>>> estimators = [
      ('dt', DecisionTreeClassifier()),
      ('svc', SVC(C=10)),
      ('gbdt', GradientBoostingClassifier(learning_rate=0.05, n_estimators=200)),
      # ('lr', LogisticRegression()),
      ('kn', KNeighborsClassifier(n_neighbors=15))
      ]
>>> ensemble_clf = StackingClassifier(
     estimators=estimators, final_estimator=LogisticRegression())



In [ ]:
cv_scores= cross_val_score(ensemble_clf, X_train, y_train, cv=5, 
                  scoring='accuracy')
print(cv_scores, cv_scores.mean())

[0.77094972 0.78089888 0.83146067 0.78651685 0.83146067] 0.8002573598644153


In [ ]:
from xgboost import XGBClassifier
clf= XGBClassifier(learning_rate=0.05, n_estimators=500)
cv_scores= cross_val_score(clf, X_train, y_train, cv=5, 
                  scoring='accuracy')
print(cv_scores, cv_scores.mean())

[0.77653631 0.79775281 0.85393258 0.80337079 0.80337079] 0.8069926558282594


# GBDT gives best accuracy so far

In [ ]:
X_test.head(5)

male  1  2  3      Fare  C  Q  S  0  1.1  2.1  Parch
0     1  0  0  1 -0.490783  0  1  0  1    0    0      0
1     0  0  0  1 -0.507479  0  0  1  0    1    0      0
2     1  0  1  0 -0.453367  0  1  0  1    0    0      0
3     1  0  0  1 -0.474005  0  0  1  1    0    0      0
4     0  0  0  1 -0.401017  0  0  1  0    1    0      1

In [ ]:
clf= GradientBoostingClassifier(learning_rate=0.05, n_estimators=200)
clf.fit(X_train, y_train)
predictions= clf.predict(X_test)

In [ ]:
for i in range(len(X_train.columns)):
  print(i, X_train.columns[i], clf.feature_importances_[i])

0 male 0.5158186799288683
1 1 0.021459319574959047
2 2 0.0021414192752737334
3 3 0.1281678085784307
4 Fare 0.250210681549682
5 C 0.003933403807104654
6 Q 0.009574262659926792
7 S 0.01693963612852724
8 0 0.0024706472808010286
9 1.1 0.0008168537373797109
10 2.1 0.016099133218877796
11 Parch 0.03236815426016893


In [ ]:
test_original= pd.read_csv('/content/drive/My Drive/titanic/test.csv')
test_original.head()

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
test_original['Survived']= predictions

In [ ]:
test_original.head(1)

PassengerId  Pclass              Name   Sex  ...    Fare  Cabin  Embarked Survived
0          892       3  Kelly, Mr. James  male  ...  7.8292    NaN         Q        0

[1 rows x 12 columns]

In [ ]:
test_original[['PassengerId', 'Survived']].to_csv('/content/drive/My Drive/titanic/gbdt_predictions.csv', index=False)

In [ ]:
(18000-1260)/18000

0.93

# To Do


In [ ]:
# create model to predict age
# fill missing age in train and test data using model
# age can be binned into 3 classes
# find feature importance in gbdt (very less usful can be eliminated)
# try adding or multiplying features to increase correlation (gender+parch)